In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('C:/Users/milan/Desktop/Studies/Data Science Course/The Data Science Course 2021 - All Resources/Part_5_Advanced_Statistical_Methods_(Machine_Learning)/S34_L219/1.02. Multiple linear regression.csv')
df.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
x = df[['SAT','Rand 1,2,3']]
y = df['GPA']

In [6]:
from sklearn.preprocessing import StandardScaler


In [8]:
scaler = StandardScaler() #this is an empty object, this will contain all standardization info

In [9]:
scaler.fit(x) #calculated mean & sd of each features and store in scaler object

StandardScaler()

In [10]:
x_scaled = scaler.transform(x) #transform the unscaled inputs using info contained in scaler object

In [11]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [12]:
reg = LinearRegression()

In [13]:
reg.fit(x_scaled,y)

LinearRegression()

In [14]:
reg.score(x_scaled,y)

0.4066811952814283

In [15]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [16]:
reg.intercept_

3.330238095238095

In [23]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']],columns = ['Features'])
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1]

In [24]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

smaller the value the less significant is the variable to the model

## Making Predictions with standardized coefficients

In [25]:
new_df = pd.DataFrame(data = [[1700,2],[1800,1]],columns = ['SAT','Rand 1,2,3'])
new_df

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [27]:
new_df_scaled = scaler.transform(new_df)

In [29]:
new_df_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [30]:
reg.predict(new_df_scaled)

array([3.09051403, 3.26413803])